remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Site settings
title: Project Pages
description: "An Integrated Scientific Blogging Template"
url: "https://projectpages.github.io"
